
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: ml-platform
  source:
    repoURL: https://github.com/yujin0131/argocd.git
    targetRevision: feature/test-argo
    path: .
    helm:
      valueFiles:
        - values.yaml
        - values/app-projects.yaml
        - values/repository.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
