---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    namespace: argocd
    name: argocd-secret
spec:
    secretStoreRef:
        kind: SecretStore
        name: argocd-secrets
    target:
        creationPolicy: Merge
        deletionPolicy: Merge
    dataFrom:
      - extract:
            key: /argocd/{{ $.Values. }}
