---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ml-platform

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 1.0.0
    helm:
      values: |
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: {{  arn:aws:iam:: :role/irsa-external-secrets}}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi

  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets-system
