{{- range .Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "argocd" }}
spec:
  description: {{ .description | default "" }}
  destinations:
    {{- range .namespaces }}
    - namespace: {{ . }}
      server: https://kubernetes.default.svc
    {{- end }}
  sourceRepos:
    - "*"
{{- end }}
