apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: ml-platform
  source:
    repoURL: https://github.com/yujin0131/argocd.git
    targetRevision: feature/test-argo
    path: .
    helm:
      valueFiles:
        - values.yaml
        - values/app-projects.yaml
        - values/repository.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: ml-platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.0.6
    helm:
      values: |
        configs:
          cm:
            url: http://localhost:8080
            dex.config: |
              connectors:
                - type: oidc
                  id: keycloak
                  name: Keycloak
                  config:
                    Issuer: https://auth.qraft.ai/realms/qraft
                    clientID: argocd-test-yujin
                    clientSecret: 13hPQRuFBQGvCwJH6JatLekXJndNoURZ
                    redirectURI: https://argocd.qraft.ai/api/dex/callback
                    requestedScopes: ["openid", "profile", "email", "groups"]
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
