---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ml-platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: {{ .Values.argocd.helmChartVersion | default "7.0.0" }}
    helm:
      releaseName: {{ .Values.argocd.releaseName | default "argocd" }}
      {{- if .Values.argocd.values }}
      values: |
{{ .Values.argocd.values | toYaml | indent 8 }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
