apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: ml-platform
  source:
    repoURL: https://github.com/yujin0131/argocd.git
    targetRevision: feature/test-argo
    path: .
    helm:
      valueFiles:
        - values/app-projects.yaml
        - values/repository.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  project: ml-platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 9.0.6
    helm:
      valueFiles:
        - values.yaml  # 공식 Helm chart 기본 값
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
