{{- range .Values.projects }}
  {{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    app.kubernetes.io/managed-by: Helm
    argocd.argoproj.io/managed-by: argocd
---
  {{- end }}
{{- end }}
