---
{{- range .Values.repositories }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "argocd" }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: {{ .url }}
  type: git
  project: {{ .project | default "default" }}
{{- end }}
