---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: ml-platform
  sources:
    # Base: official Helm chart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.0.6
      helm:
        releaseName: argocd
        valueFiles:
          - $values/values.yaml
          - $values/values/app-projects.yaml
          - $values/values/repository.yaml
        ignoreMissingValueFiles: true

    # Overrides & custom manifests (values, templates, policies)
    - repoURL: https://github.com/yujin0131/argocd.git
      targetRevision: feature/test-argo
      ref: values
      path: ..

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
